services:
  postgres:
    image: ankane/pgvector:latest
    container_name: research_db
    ports:
      -"5432:5432"
    volumes:
      -pgdata: /var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passcode
      POSTGRES_DB: research_storage
volumes:
  pgdata: